### ISSUE TITLE
Add option to use another main branch apart from 'master'

### ISSUE THREAD

**Issue by raducoriu** [neuecc/Open-on-GitHub#26]
Some repos have different default branches from 'master' and there is not configuration to change that

**Comment by neuecc** [comment]
Currently retrieve from `main` or `master` or `develop`.
https://github.com/neuecc/Open-on-GitHub/blob/master/OpenOnGitHub/GitRepository.cs#L54-L55
Yes, it is not configurable.

**Comment by raducoriu** [comment]
I saw that and that's why I filed this issue/suggestion.
Even that doesn't seem to work properly for our repo. We have 'develop' as our main branch and 'main' doesn't even exist, but still 'main' is shown in the open menu. Might be that the `.Branches` or `.FriendlyName` calls fail.
Anyway, even a text file config would be ok for this.

**Comment by danielcoppa-olo** [comment]
That line will never resolve to anything but "main". The FriendlyNames are all prefixed with "origin", so it will never match. Does the string `"develop"` contain the string `"origin/develop"`? No.

There's another usage further down in that class, and there, the prefix is correctly removed before use: https://github.com/neuecc/Open-on-GitHub/blob/a6f3c0537965730013c35d9f6359f328a0013e7c/OpenOnGitHub/GitRepository.cs#L72

The prefix needs to be removed before comparing. Alternatively, invert the comparison so that it is checking if `"origin/develop"` contains `"develop"`, instead of the reverse.

**Comment by neuecc** [comment]
To begin with, that code was not released.
It was newly released in 2.1.0, so I think it includes support.

**Comment by meum** [comment]
Having this configurable would be great. We use `development` as the main branch

**Comment by neuecc** [comment]
v 2.1.1 adds develop(development) in menu if branch exists.

**Comment by meum** [comment]
I tried v 2.1.1 and i'm still seeing `main` in the menu, even though we have a `development` branch and no `main` branch

**Comment by raducoriu** [comment]
I think there is a bug (maybe here https://github.com/neuecc/Open-on-GitHub/blob/a6f3c0537965730013c35d9f6359f328a0013e7c/OpenOnGitHub/GitRepository.cs#L55) as Daniel pointed out before. At line 77 the "origin/" prefix is removed, but at line 55 it's not.

**Comment by neuecc** [comment]
I think that prefix removal is irrelevant because it is comparing with Contains.
However, I've made a few modifications to the logic.
I think it's working on my environment, so I'll release it soon, so please try it out.
![image](https://github.com/user-attachments/assets/42186b47-20e6-453f-bd2f-3726469883db)

**Comment by neuecc** [comment]
released 2.1.2.

**Comment by meum** [comment]
i see `development` now, thanks!

**Comment by raducoriu** [comment]
> I think that prefix removal is irrelevant because it is comparing with Contains. However, I've made a few modifications to the logic. I think it's working on my environment, so I'll release it soon, so please try it out. ![image](https://private-user-images.githubusercontent.com/46207/384301372-42186b47-20e6-453f-bd2f-3726469883db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMzY3MTAsIm5iZiI6MTczMTMzNjQxMCwicGF0aCI6Ii80NjIwNy8zODQzMDEzNzItNDIxODZiNDctMjBlNi00NTNmLWJkMmYtMzcyNjQ2OTg4M2RiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDE0NDY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhN2M3ZTBkNThiN2JjNWE5YjBjZGI3Y2JhMjNiYmM2OWZhNjA4NjBkY2EzNTU2Yjg1OTBjZDI2YTE3MWE3OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.odCEcmMXStyKhODHtBrMRrM9DJu7xXHuPm45TOrU0Vg)

You are using `Contains` on an array that doesn't contain prefixes: `new[] { "main", "master", "develop" }.Contains("origin/develop")`

**Comment by neuecc** [comment]
You're right - it was an embarrassing mistake, and preconceptions are scary things because I hadn't noticed it at all! 
Now I've changed it to a simple comparison, so there shouldn't be any mistakes this time...
https://github.com/neuecc/Open-on-GitHub/blob/8b799544a9fb9f189223a82dc3af1dcfcade0ceb/OpenOnGitHub/GitRepository.cs#L57
